### ISSUE TITLE
404 page error when reloading Single.js on firebase

### ISSUE THREAD

**Issue by TheoMer** [wesbos/Simple-Redux#15]
OS: Windows 10 Pro
Firebase: 3.2.3

Steps:

```
1.	 Login to Firebase (or Signup if you don't have an account) and create a new project
2.	 Install cli: npm i -g firebase-tools
3.	 Login: firebase login
4.	 Initialize project with firebase init then answer:
         •	What file should be used for Database Rules? -> database.rules.json
         •	What do you want to use as your public directory? -> public
         •	Configure as a single-page app (rewrite all urls to /index.html)? -> No
         •	What Firebase project do you want to associate as default? -> your Firebase project name
5.	 Build Project: npm run build (For windows users)
6.	 Confirm Firebase config by running locally: firebase serve
7.	 Deploy to firebase: firebase deploy
```

After clicking an image on the main page (PhotoGrid.js) and being redirected to Single.js, reloading the page causes the following server error:

`127.0.0.1 - - [15/Feb/2017:10:34:40 +0000] "GET /view/-1rhFawccs HTTP/1.1" 404 7005 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36 OPR/43.0.2442.806"`

You can see this in action by viewing my own firebase implementation of the project here: https://learn-redux.firebaseapp.com

**Comment by TheoMer** [comment]
During the 'firebase init' process, for React Router, you do in fact want to say Yes to "Configure as a single-page app." during the 'firebase init' of your project folder.

A rewrite is added to firebase. json file:

```
{
  "database": {
    "rules": "database.rules.json"
  },
  "hosting": {
    "public": "public",
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
```

**Comment by niranjanneeru** [comment]
Now I am unable to set a custom 404 page
